name: web_client
description: A minimal jaspr web app.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  mobx:
  jaspr:

  bootstrap_dart:
    git:
      url: https://github.com/juancastillo0/bootstrap_dart.git
  jaspr_bootstrap:
    git:
      url: https://github.com/juancastillo0/bootstrap_dart.git
      path: packages/jaspr_bootstrap

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
  webdev: 2.7.7
  mobx_codegen: ^2.0.7

dependency_overrides:
  jaspr:
    git:
      url: https://github.com/juancastillo0/jaspr.git
      ref: heads/observer_component_wip_v2
      path: packages/jaspr
    # path: ../../jaspr/packages/jaspr
  universal_html:
    git:
      url: https://github.com/juancastillo0/universal_html.git
      ref: heads/sdk_exports
    # path: ../../universal_html
