name: web_client
description: A minimal jaspr web app.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  mobx:
  jaspr:
    git:
      url: https://github.com/schultek/jaspr.git
      path: packages/jaspr
      ref: a71f766cd78e23fbadccf92862c2b27e08f5a0fa

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
  webdev: 2.7.7
