targets:
  $default:
    builders:
      graphql_codegen:
        options:
          addTypenameExcludedPaths:
            - subscription
          scalars:
            Date:
              type: DateTime
          clients:
            - graphql
