name: dart_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  graphql: ^5.1.2-beta.4
  json_annotation: ^4.6.0
  mobx: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  graphql_codegen: ^0.11.0-beta.4
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
